title: "kat"
description: "Cybersec and other Stuff"
url: "https://katiemeo.ws"
baseurl: ""

author:
  name: "kat"
  email: "kat@katiemeo.ws"

permalink: /writeups/:title/
timezone: Europe/Vienna
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
